### ISSUE TITLE
Unable to delete Kustomization controller from EKS.

### ISSUE THREAD

**Issue by qspors** [fluxcd/kustomize-controller#666] opened 2022-05-27 00:33 UTC
Hello.
I'm using TF for fluxv2 deployment (https://github.com/fluxcd/terraform-provider-flux/tree/main/examples/gitlab) on my AWS EKS cluster v.1.22 , fluxv2 provider 0.14.1
After deployment everything is good. Flux working perfectly, no issues.
But when I'm trying to delete fluxv2 from cluster ( tried to delete thru TF, "terraform destroy" and manually thru kubectl), deleting is hangs on kustomizations.kustomize.toolkit.fluxcd.io crd.
I tried to get events but nothing. No events no logs.
Also I cant delete resources thru namespace deletion (kubectl delete namespace flux-system --force) deleting of namespace accordingly hangs too.

**Comment by stefanprodan** [comment] 2022-05-27 05:50
Yes this a know Terraform limitation, as it doesn’t know how to delete things in order. To uninstall Flux from your cluster, you need to use our CLI `flux uninstall` docs here: https://fluxcd.io/docs/installation/#uninstall

Duplicate of: https://github.com/fluxcd/terraform-provider-flux/issues/91

**Closed by stefanprodan** 2022-05-27 05:50 UTC
