### ISSUE TITLE
Ingress resource pruned during update with api migration

### ISSUE THREAD

**Issue by tbomberg** [fluxcd/kustomize-controller#510] opened 2021-12-06 11:19 UTC
Hi,

i just encountered some strange behavior of flux during migration of the manifests of Ingress resources.

When I update an Ingress resource from `apiVersion: extensions/v1beta1` to `apiVersion: networking.k8s.io/v1`
it gets deleted first and only in the next routine reconciliation run it gets recreated. 

Depending on the reconciliation interval it can mean quite some disruption to the deployed services.

Environment:
  K8S: 1.20.7
  Flux: v0.21.1 + v0.24.0

Logs from the kustomize-controller:

```
{"level":"info","ts":"2021-12-06T11:03:36.171Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"testing","namespace":"flux-system","output":{"Namespace/echo":"created"}}
{"level":"info","ts":"2021-12-06T11:03:36.738Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"testing","namespace":"flux-system","output":{"Deployment/echo/echo":"created","Ingress/echo/echo":"created","Service/echo/echo-service":"created"}}
{"level":"info","ts":"2021-12-06T11:04:29.043Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"testing","namespace":"flux-system","output":{"Namespace/echo":"unchanged"}}
{"level":"info","ts":"2021-12-06T11:04:29.224Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"testing","namespace":"flux-system","output":{"Deployment/echo/echo":"unchanged","Ingress/echo/echo":"configured","Service/echo/echo-service":"unchanged"}}
**{"level":"info","ts":"2021-12-06T11:04:29.252Z","logger":"controller.kustomization","msg":"garbage collection completed: Ingress/echo/echo deleted","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"testing","namespace":"flux-system"}**
{"level":"info","ts":"2021-12-06T11:08:36.013Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"testing","namespace":"flux-system","output":{"Namespace/echo":"unchanged"}}
{"level":"info","ts":"2021-12-06T11:08:36.379Z","logger":"controller.kustomization","msg":"server-side apply completed","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"testing","namespace":"flux-system","output":{"Deployment/echo/echo":"unchanged","Ingress/echo/echo":"created","Service/echo/echo-service":"unchanged"}}
````

**Comment by stefanprodan** [comment] 2021-12-09 10:14
Yes this is the expected behaviour when the API group changes, Flux uses the same mechanism as RBAC to track objects, an object ID is composed of API Group, API Kind, Name and Namespace. The workaround is to disable pruning when the API group changes.

**Comment by kingdonb** [comment] 2021-12-15 21:51
To be super clear, this only affects resources when their API **group** changes, not only API **version**.

Flux is smart enough to know that `kustomization.toolkit.fluxcd.io/v1beta2` is the successor to `kustomization.toolkit.fluxcd.io/v1beta1` because they have the same group, but when the group changes we would need a really ugly special case to handle this, as Flux has no way to know `Ingress` resources migrated from the `extensions` to `networking` API group.

I agree we wouldn't want to set a precedent of adding these types of special cases, and hopefully we don't see this happening to APIs in many more cases in the future. Hopefully Ingress is only moving API groups once, and it's much worse for Flux to carry this special case around forever, it would be better for users to handle this by disabling pruning.

Disable pruning before the upgrade, then re-enable it, (finally, get your infrastructure beyond the K8s 1.22 upgrade, which disables the extensions/Ingress API permanently, so no more extensions/v1beta1 ingresses will validate or can creep into the configuration, so you only have to do this once...)

As there is a `wontfix` label applied here, I'm going to go ahead and close the issue. Thanks for the report!

**Closed by kingdonb** 2021-12-15 21:51 UTC
Labels: wontfix
