### ISSUE TITLE
Garbage Collector will remove resources from errored Kustomization

### ISSUE THREAD

**Issue by apeschel** [fluxcd/kustomize-controller#340] opened 2021-05-03 21:31 UTC
It's possible to have a kustomization with an error that causes a resource to cease rendering. The kustomization's reconciliation will fail with an error, but the garbage collector will remove the resource, despite the kustomazation never actually completing cleanly.

Allowing the garbage collector to prune resources that are part of a failed kustomization opens up a large class of potential problems that I would categorize as bugs.

**Comment by stefanprodan** [comment] 2021-05-04 06:58
Can you provide an example to reproduce this? I don’t see how this is possible since a failed apply stops the reconciliation and it will never get to garbage collection.

**Comment by stefanprodan** [comment] 2021-06-11 11:29
Going to close this as I can't reproduce it, not anyone provided an example.

**Closed by stefanprodan** 2021-06-11 11:29 UTC
